# Generated by Django 4.1.3 on 2022-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panely_pvh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('image', models.FileField(upload_to='panely/img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Панель',
                'verbose_name_plural': 'Панели',
            },
        ),
    ]
