# Generated by Django 4.1.3 on 2022-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panely', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ugolky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('image', models.FileField(upload_to='panely/img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Угол ПВХ',
                'verbose_name_plural': 'Углы ПВХ',
            },
        ),
    ]
